version: "3"
services:
    db: 
        image: postgres
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: slack
    redis:
        image: "redis"
        networks:
            - webnet
        ports:
            - "6379:6379"
    web: 
        image: slack
        ports:
            - "5000:5000"
        networks:
            - webnet
        environment:
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_POST: 6379
            PORT: 5000
            SECRET: 854917c1396298258e5d59560bf8382c0895e9d5
            SECRET2: 8SDKqsdkqsdS88qsdqsd6dsqdkq987SQDDBJSD8d
        command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
networks: 
    webnet: 